### ISSUE TITLE
SyntaxError: Unexpected identifier in node-website-course/views/pages/about.ejs while compiling ejs

### ISSUE THREAD

**Issue by tempcke** [scotch-io/node-website-course#1]
When watching your video and following along I got this error, so I cloned our source from here and executed it and got the same error.  Only thing I can figure is that there was a breaking change in one of your dependencies in package.json

```
SyntaxError: Unexpected identifier in /home/tempcke/node-website-course/views/pages/about.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
   at Object.Function (<anonymous>)
   at Object.Template.compile (/home/tempcke/node-website-course/node_modules/ejs/lib/ejs.js:481:12)
   at Object.compile (/home/tempcke/node-website-course/node_modules/ejs/lib/ejs.js:290:16)
   at handleCache (/home/tempcke/node-website-course/node_modules/ejs/lib/ejs.js:168:18)
   at View.exports.renderFile [as engine] (/home/tempcke/node-website-course/node_modules/ejs/lib/ejs.js:364:14)
   at View.render (/home/tempcke/node-website-course/node_modules/express/lib/view.js:126:8)
   at tryRender (/home/tempcke/node-website-course/node_modules/express/lib/application.js:639:10)
   at EventEmitter.render (/home/tempcke/node-website-course/node_modules/express/lib/application.js:591:3)
   at ServerResponse.render (/home/tempcke/node-website-course/node_modules/express/lib/response.js:960:7)
   at ServerResponse.res.render (/home/tempcke/node-website-course/node_modules/express-ejs-layouts/lib/express-layouts.js:77:12) 
```

**Comment by chris-sev** [comment]
Hey, I just cloned this down, and ran:

```
npm install
node server.js
```

Was able to view the site in <http://localhost:8080>. 

What version of Node are you running? Maybe that has something to do with it

**Comment by tempcke** [comment]
Hi, thank you for your reply.
```
$ nodejs -v
v0.10.25
$ npm -v
1.3.10
$ nodemon -v
1.10.2

```

**Comment by chris-sev** [comment]
@tempcke Do you have your code in a GitHub repo we could take a look at?

**Comment by tempcke** [comment]
@sevilayha no, we are new to node and we were just going though the video tutorial and ran into this issue.  So I did a pull of this repo and ran `npm install` and `node server.js` to see if it worked (which would indicate to me that we made a mistake in one of the tutorial steps)  So the code we were using is this repo itself .. host machine is running linux mint 17.3  .. not sure what other information we could provide that could help explain why it isn't working for us.

**Comment by hollylawly** [comment]
I think you need to upgrade to a newer version of Node (at least 4.0) and that should solve it. You can use `nvm` to easily [manage your Node versions](https://davidwalsh.name/nvm) if you're on `0.10.25` for a specific reason.

**Comment by tempcke** [comment]
upgraded to node 7 
no idea why i was on 0.10.25 .. either i was reading an old tutorial that installed that specific version or that was the version in the ubuntu repos that ship with mint 17 .. which should be ubuntu 14.04 i think...

at any rate .. it is fixed.  thanks!

**Comment by rahul-rk51** [comment]
if  inside ejs  you have any spelling mistakes like= //<% for (ver i=0; i<newitems.length; i++) { %>//     
// <% for (var i=0; i<newitems.length; i++) { %>//
 or
something you missed -,=.....
<%-        %> 
<%=       %>
just look carefully 😃
